# Generated by Django 4.1.1 on 2022-09-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oks',
            name='adr_oks',
            field=models.TextField(blank=True, verbose_name='Адрес объекта'),
        ),
    ]
